### ISSUE TITLE
Comments aren't working

### ISSUE THREAD

**Issue by Edo78** [Kerwood/linuxblog-xyz#2]
I logged in but the system doesn't let me comment and it faill to load other comments
![image](https://user-images.githubusercontent.com/3602209/123554479-7eea4480-d780-11eb-94e6-c1de0d35e811.png)

**Comment by Kerwood** [comment]
Thanks for the heads up. I'll see if I can fix it :)

**Comment by Kerwood** [comment]
Hmm I cant seem to replicate the issue. Have you tried a different browser ?
![image](https://user-images.githubusercontent.com/4029521/123555257-f02bf680-d784-11eb-81e7-eae418a6981e.png)

**Comment by Edo78** [comment]
I tried in another browser and I still get the same issue. I check the Vssue demo on their site and it's working properly.

I checked through their issues and I found this one https://github.com/meteorlxy/vssue/issues/34 could it be the same case?
It looks like to comment a issue must already exists ... Do you have a page with comments so that I could check if I can add a comment there?

**Comment by Kerwood** [comment]
Hmm it definitely look like the same issue. I think maybe Vssue oauth app need the be the owner of the github issue for it to work. 

Have a look at https://linuxblog.xyz/posts/flexget-container/

**Comment by Edo78** [comment]
On that page I can write a comment.

**Comment by Kerwood** [comment]
Great. I have created issues for each page. Thank you very much for your help :)
It is much appreciated.

**Comment by Edo78** [comment]
Thank you, now I can write a comment asking for your help ;)
