### ISSUE TITLE
Instructions in netboot-docker-compose for Mikrotik fail

### ISSUE THREAD

**Issue by alexjs** [Kerwood/linuxblog-xyz#48]
Using the command in this blogpost throws an error on the current (as of Jan 2024) Mikrotik OS

`[admin@MikroTik] > /ip dhcp-server network set 0 next-server="'10.91.1.20'"
invalid value for argument next-server`

Removing the extra 's wrapping the next-server argument seems to be fine - but I'm not sure if there's another ramification, so opening as an issue instead of a PR to double check :)

Nice blog, thanks for publishing it!

**Comment by Kerwood** [comment]
Yes, you are right. Thank you :)
